sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rBcHydcul+tWmpmlq4sqt9EhGHkI+TyHSguMYMqW/ETO+X/0wM45QwhT6Uz+58LJXV+KPRgfHBCp9KjUhtbs5hBFRxbwkjLWtn/xHSmmHHR4/AOPN9IcnhpNIpFyZIlm/WrHxuKxDGXKnfcXsvTDZypMc96ZxNTwr8Ak/zVJJL95a42yMhnf7gNQR6eYH74PBPclJ/TAf4WDTbQte82sOqc0LrRJY8aoNDH67CSorhsW9ok4fHiUENZwQ9pTc99hJkX/rXaGGnQ21Su0ATsauJL/4qoIR3Es3cZMDB2XQkie+/wDTNRy31T3Lwg9727lwO8kr2msQSr1nl8oyPa3g8w1iCjHZgOosVhpV5oVzvf6VSsWWqoOJji7C7t+O2LZOBmfsDbJg4ni/bgP27vHz0eMTA0KZgaKU3ICTgcIXmtfASnipUf5Y7z1vBAm5x3T63wFuKL6fkR36HKIly/efP6omYvYdKK8Fq4FNVvWLWqbOAU7E45sJdMJ3cy2l5CRb6kpuG/gkO/ciI/ANluWsJFDaWMXRQxdpyIZhnFUGldVVV0/KsaM6j/h/y910LcQ0ZdYpg5hW4McgxEQOLzVeSR/jJ0bhpO0M1LWdLcn6pLgkImLcVGiEYP4wP9Fe52YedHnJgqd3cvVLpQ6RNkToMm3XxKJpBxcxkZ5mSR8Lqk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Letters-of-Two-Brides_1941
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy